version: "3.9"
services:
  api:
    build: ./backend
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/miniblog
      - JWT_SECRET=change_me
    ports: ["4000:4000"]
    depends_on: [mongo]
  web:
    build: ./frontend
    ports: ["5173:5173"]
    depends_on: [api]
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
